//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
    
        public virtual Customer customer { get; set; }
    }
}
