//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_api_demo.TPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Attribute", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Attribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((this.ParentIDField.Equals(value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private tp_api_demo.TPServiceReference.CustomerAddress[] AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tp_api_demo.TPServiceReference.CustomerAddress[] Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerAddress", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class CustomerAddress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturer", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private tp_api_demo.TPServiceReference.OrderProduct[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postcode {
            get {
                return this.PostcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostcodeField, value) != true)) {
                    this.PostcodeField = value;
                    this.RaisePropertyChanged("Postcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tp_api_demo.TPServiceReference.OrderProduct[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderProduct", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class OrderProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class OrderStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private tp_api_demo.TPServiceReference.ProductAttribute[] AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManufacturerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tp_api_demo.TPServiceReference.ProductAttribute[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManufacturerID {
            get {
                return this.ManufacturerIDField;
            }
            set {
                if ((this.ManufacturerIDField.Equals(value) != true)) {
                    this.ManufacturerIDField = value;
                    this.RaisePropertyChanged("ManufacturerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusID {
            get {
                return this.StatusIDField;
            }
            set {
                if ((this.StatusIDField.Equals(value) != true)) {
                    this.StatusIDField = value;
                    this.RaisePropertyChanged("StatusID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductAttribute", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class ProductAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttributeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttributeID {
            get {
                return this.AttributeIDField;
            }
            set {
                if ((this.AttributeIDField.Equals(value) != true)) {
                    this.AttributeIDField = value;
                    this.RaisePropertyChanged("AttributeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductStatus", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class ProductStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderRequest", Namespace="http://schemas.datacontract.org/2004/07/tp_lab.api.types")]
    [System.SerializableAttribute()]
    public partial class OrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private tp_api_demo.TPServiceReference.OrderProduct[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AddressID {
            get {
                return this.AddressIDField;
            }
            set {
                if ((this.AddressIDField.Equals(value) != true)) {
                    this.AddressIDField = value;
                    this.RaisePropertyChanged("AddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public tp_api_demo.TPServiceReference.OrderProduct[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TPServiceReference.ITPService")]
    public interface ITPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetAttribute", ReplyAction="http://tempuri.org/ITPService/GetAttributeResponse")]
        tp_api_demo.TPServiceReference.Attribute GetAttribute(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetAttribute", ReplyAction="http://tempuri.org/ITPService/GetAttributeResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Attribute> GetAttributeAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCategory", ReplyAction="http://tempuri.org/ITPService/GetCategoryResponse")]
        tp_api_demo.TPServiceReference.Category GetCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCategory", ReplyAction="http://tempuri.org/ITPService/GetCategoryResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Category> GetCategoryAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomer", ReplyAction="http://tempuri.org/ITPService/GetCustomerResponse")]
        tp_api_demo.TPServiceReference.Customer GetCustomer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomer", ReplyAction="http://tempuri.org/ITPService/GetCustomerResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Customer> GetCustomerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomerAddress", ReplyAction="http://tempuri.org/ITPService/GetCustomerAddressResponse")]
        tp_api_demo.TPServiceReference.CustomerAddress GetCustomerAddress(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomerAddress", ReplyAction="http://tempuri.org/ITPService/GetCustomerAddressResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.CustomerAddress> GetCustomerAddressAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetManufacturer", ReplyAction="http://tempuri.org/ITPService/GetManufacturerResponse")]
        tp_api_demo.TPServiceReference.Manufacturer GetManufacturer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetManufacturer", ReplyAction="http://tempuri.org/ITPService/GetManufacturerResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Manufacturer> GetManufacturerAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrder", ReplyAction="http://tempuri.org/ITPService/GetOrderResponse")]
        tp_api_demo.TPServiceReference.Order GetOrder(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrder", ReplyAction="http://tempuri.org/ITPService/GetOrderResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Order> GetOrderAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrderStatus", ReplyAction="http://tempuri.org/ITPService/GetOrderStatusResponse")]
        tp_api_demo.TPServiceReference.OrderStatus GetOrderStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrderStatus", ReplyAction="http://tempuri.org/ITPService/GetOrderStatusResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.OrderStatus> GetOrderStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProduct", ReplyAction="http://tempuri.org/ITPService/GetProductResponse")]
        tp_api_demo.TPServiceReference.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProduct", ReplyAction="http://tempuri.org/ITPService/GetProductResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProductStatus", ReplyAction="http://tempuri.org/ITPService/GetProductStatusResponse")]
        tp_api_demo.TPServiceReference.ProductStatus GetProductStatus(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProductStatus", ReplyAction="http://tempuri.org/ITPService/GetProductStatusResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.ProductStatus> GetProductStatusAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetAttributes", ReplyAction="http://tempuri.org/ITPService/GetAttributesResponse")]
        tp_api_demo.TPServiceReference.Attribute[] GetAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetAttributes", ReplyAction="http://tempuri.org/ITPService/GetAttributesResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Attribute[]> GetAttributesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCategories", ReplyAction="http://tempuri.org/ITPService/GetCategoriesResponse")]
        tp_api_demo.TPServiceReference.Category[] GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCategories", ReplyAction="http://tempuri.org/ITPService/GetCategoriesResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Category[]> GetCategoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomers", ReplyAction="http://tempuri.org/ITPService/GetCustomersResponse")]
        tp_api_demo.TPServiceReference.Customer[] GetCustomers(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomers", ReplyAction="http://tempuri.org/ITPService/GetCustomersResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Customer[]> GetCustomersAsync(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomerAddresses", ReplyAction="http://tempuri.org/ITPService/GetCustomerAddressesResponse")]
        tp_api_demo.TPServiceReference.CustomerAddress[] GetCustomerAddresses(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetCustomerAddresses", ReplyAction="http://tempuri.org/ITPService/GetCustomerAddressesResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.CustomerAddress[]> GetCustomerAddressesAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetManufacturers", ReplyAction="http://tempuri.org/ITPService/GetManufacturersResponse")]
        tp_api_demo.TPServiceReference.Manufacturer[] GetManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetManufacturers", ReplyAction="http://tempuri.org/ITPService/GetManufacturersResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Manufacturer[]> GetManufacturersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrders", ReplyAction="http://tempuri.org/ITPService/GetOrdersResponse")]
        tp_api_demo.TPServiceReference.Order[] GetOrders(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrders", ReplyAction="http://tempuri.org/ITPService/GetOrdersResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Order[]> GetOrdersAsync(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrderProducts", ReplyAction="http://tempuri.org/ITPService/GetOrderProductsResponse")]
        tp_api_demo.TPServiceReference.OrderProduct[] GetOrderProducts(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetOrderProducts", ReplyAction="http://tempuri.org/ITPService/GetOrderProductsResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.OrderProduct[]> GetOrderProductsAsync(int order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProducts", ReplyAction="http://tempuri.org/ITPService/GetProductsResponse")]
        tp_api_demo.TPServiceReference.Product[] GetProducts(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/GetProducts", ReplyAction="http://tempuri.org/ITPService/GetProductsResponse")]
        System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Product[]> GetProductsAsync(int skip, int count);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCustomerAddress", ReplyAction="http://tempuri.org/ITPService/AddCustomerAddressResponse")]
        int AddCustomerAddress(tp_api_demo.TPServiceReference.CustomerAddress value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCustomerAddress", ReplyAction="http://tempuri.org/ITPService/AddCustomerAddressResponse")]
        System.Threading.Tasks.Task<int> AddCustomerAddressAsync(tp_api_demo.TPServiceReference.CustomerAddress value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddAttribute", ReplyAction="http://tempuri.org/ITPService/AddAttributeResponse")]
        int AddAttribute(tp_api_demo.TPServiceReference.Attribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddAttribute", ReplyAction="http://tempuri.org/ITPService/AddAttributeResponse")]
        System.Threading.Tasks.Task<int> AddAttributeAsync(tp_api_demo.TPServiceReference.Attribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCategory", ReplyAction="http://tempuri.org/ITPService/AddCategoryResponse")]
        int AddCategory(tp_api_demo.TPServiceReference.Category value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCategory", ReplyAction="http://tempuri.org/ITPService/AddCategoryResponse")]
        System.Threading.Tasks.Task<int> AddCategoryAsync(tp_api_demo.TPServiceReference.Category value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCustomer", ReplyAction="http://tempuri.org/ITPService/AddCustomerResponse")]
        int AddCustomer(tp_api_demo.TPServiceReference.Customer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddCustomer", ReplyAction="http://tempuri.org/ITPService/AddCustomerResponse")]
        System.Threading.Tasks.Task<int> AddCustomerAsync(tp_api_demo.TPServiceReference.Customer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddManufacturer", ReplyAction="http://tempuri.org/ITPService/AddManufacturerResponse")]
        int AddManufacturer(tp_api_demo.TPServiceReference.Manufacturer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddManufacturer", ReplyAction="http://tempuri.org/ITPService/AddManufacturerResponse")]
        System.Threading.Tasks.Task<int> AddManufacturerAsync(tp_api_demo.TPServiceReference.Manufacturer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddOrder", ReplyAction="http://tempuri.org/ITPService/AddOrderResponse")]
        int AddOrder(tp_api_demo.TPServiceReference.OrderRequest value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddOrder", ReplyAction="http://tempuri.org/ITPService/AddOrderResponse")]
        System.Threading.Tasks.Task<int> AddOrderAsync(tp_api_demo.TPServiceReference.OrderRequest value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddOrderStatus", ReplyAction="http://tempuri.org/ITPService/AddOrderStatusResponse")]
        int AddOrderStatus(tp_api_demo.TPServiceReference.OrderStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddOrderStatus", ReplyAction="http://tempuri.org/ITPService/AddOrderStatusResponse")]
        System.Threading.Tasks.Task<int> AddOrderStatusAsync(tp_api_demo.TPServiceReference.OrderStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProduct", ReplyAction="http://tempuri.org/ITPService/AddProductResponse")]
        int AddProduct(tp_api_demo.TPServiceReference.Product value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProduct", ReplyAction="http://tempuri.org/ITPService/AddProductResponse")]
        System.Threading.Tasks.Task<int> AddProductAsync(tp_api_demo.TPServiceReference.Product value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProductAttribute", ReplyAction="http://tempuri.org/ITPService/AddProductAttributeResponse")]
        int AddProductAttribute(tp_api_demo.TPServiceReference.ProductAttribute v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProductAttribute", ReplyAction="http://tempuri.org/ITPService/AddProductAttributeResponse")]
        System.Threading.Tasks.Task<int> AddProductAttributeAsync(tp_api_demo.TPServiceReference.ProductAttribute v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProductStatus", ReplyAction="http://tempuri.org/ITPService/AddProductStatusResponse")]
        int AddProductStatus(tp_api_demo.TPServiceReference.ProductStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/AddProductStatus", ReplyAction="http://tempuri.org/ITPService/AddProductStatusResponse")]
        System.Threading.Tasks.Task<int> AddProductStatusAsync(tp_api_demo.TPServiceReference.ProductStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetAttribute", ReplyAction="http://tempuri.org/ITPService/SetAttributeResponse")]
        bool SetAttribute(tp_api_demo.TPServiceReference.Attribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetAttribute", ReplyAction="http://tempuri.org/ITPService/SetAttributeResponse")]
        System.Threading.Tasks.Task<bool> SetAttributeAsync(tp_api_demo.TPServiceReference.Attribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCategory", ReplyAction="http://tempuri.org/ITPService/SetCategoryResponse")]
        bool SetCategory(tp_api_demo.TPServiceReference.Category value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCategory", ReplyAction="http://tempuri.org/ITPService/SetCategoryResponse")]
        System.Threading.Tasks.Task<bool> SetCategoryAsync(tp_api_demo.TPServiceReference.Category value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCustomer", ReplyAction="http://tempuri.org/ITPService/SetCustomerResponse")]
        bool SetCustomer(tp_api_demo.TPServiceReference.Customer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCustomer", ReplyAction="http://tempuri.org/ITPService/SetCustomerResponse")]
        System.Threading.Tasks.Task<bool> SetCustomerAsync(tp_api_demo.TPServiceReference.Customer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCustomerAddress", ReplyAction="http://tempuri.org/ITPService/SetCustomerAddressResponse")]
        bool SetCustomerAddress(tp_api_demo.TPServiceReference.CustomerAddress value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetCustomerAddress", ReplyAction="http://tempuri.org/ITPService/SetCustomerAddressResponse")]
        System.Threading.Tasks.Task<bool> SetCustomerAddressAsync(tp_api_demo.TPServiceReference.CustomerAddress value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetManufacturer", ReplyAction="http://tempuri.org/ITPService/SetManufacturerResponse")]
        bool SetManufacturer(tp_api_demo.TPServiceReference.Manufacturer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetManufacturer", ReplyAction="http://tempuri.org/ITPService/SetManufacturerResponse")]
        System.Threading.Tasks.Task<bool> SetManufacturerAsync(tp_api_demo.TPServiceReference.Manufacturer value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetOrderStatus", ReplyAction="http://tempuri.org/ITPService/SetOrderStatusResponse")]
        bool SetOrderStatus(tp_api_demo.TPServiceReference.OrderStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetOrderStatus", ReplyAction="http://tempuri.org/ITPService/SetOrderStatusResponse")]
        System.Threading.Tasks.Task<bool> SetOrderStatusAsync(tp_api_demo.TPServiceReference.OrderStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProduct", ReplyAction="http://tempuri.org/ITPService/SetProductResponse")]
        bool SetProduct(tp_api_demo.TPServiceReference.Product value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProduct", ReplyAction="http://tempuri.org/ITPService/SetProductResponse")]
        System.Threading.Tasks.Task<bool> SetProductAsync(tp_api_demo.TPServiceReference.Product value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProductAttribute", ReplyAction="http://tempuri.org/ITPService/SetProductAttributeResponse")]
        bool SetProductAttribute(tp_api_demo.TPServiceReference.ProductAttribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProductAttribute", ReplyAction="http://tempuri.org/ITPService/SetProductAttributeResponse")]
        System.Threading.Tasks.Task<bool> SetProductAttributeAsync(tp_api_demo.TPServiceReference.ProductAttribute value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProductStatus", ReplyAction="http://tempuri.org/ITPService/SetProductStatusResponse")]
        bool SetProductStatus(tp_api_demo.TPServiceReference.ProductStatus value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITPService/SetProductStatus", ReplyAction="http://tempuri.org/ITPService/SetProductStatusResponse")]
        System.Threading.Tasks.Task<bool> SetProductStatusAsync(tp_api_demo.TPServiceReference.ProductStatus value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITPServiceChannel : tp_api_demo.TPServiceReference.ITPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TPServiceClient : System.ServiceModel.ClientBase<tp_api_demo.TPServiceReference.ITPService>, tp_api_demo.TPServiceReference.ITPService {
        
        public TPServiceClient() {
        }
        
        public TPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public tp_api_demo.TPServiceReference.Attribute GetAttribute(int id) {
            return base.Channel.GetAttribute(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Attribute> GetAttributeAsync(int id) {
            return base.Channel.GetAttributeAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Category GetCategory(int id) {
            return base.Channel.GetCategory(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Category> GetCategoryAsync(int id) {
            return base.Channel.GetCategoryAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Customer GetCustomer(int id) {
            return base.Channel.GetCustomer(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Customer> GetCustomerAsync(int id) {
            return base.Channel.GetCustomerAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.CustomerAddress GetCustomerAddress(int id) {
            return base.Channel.GetCustomerAddress(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.CustomerAddress> GetCustomerAddressAsync(int id) {
            return base.Channel.GetCustomerAddressAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Manufacturer GetManufacturer(int id) {
            return base.Channel.GetManufacturer(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Manufacturer> GetManufacturerAsync(int id) {
            return base.Channel.GetManufacturerAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Order GetOrder(int id) {
            return base.Channel.GetOrder(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Order> GetOrderAsync(int id) {
            return base.Channel.GetOrderAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.OrderStatus GetOrderStatus(int id) {
            return base.Channel.GetOrderStatus(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.OrderStatus> GetOrderStatusAsync(int id) {
            return base.Channel.GetOrderStatusAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.ProductStatus GetProductStatus(int id) {
            return base.Channel.GetProductStatus(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.ProductStatus> GetProductStatusAsync(int id) {
            return base.Channel.GetProductStatusAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Attribute[] GetAttributes() {
            return base.Channel.GetAttributes();
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Attribute[]> GetAttributesAsync() {
            return base.Channel.GetAttributesAsync();
        }
        
        public tp_api_demo.TPServiceReference.Category[] GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Category[]> GetCategoriesAsync() {
            return base.Channel.GetCategoriesAsync();
        }
        
        public tp_api_demo.TPServiceReference.Customer[] GetCustomers(int skip, int count) {
            return base.Channel.GetCustomers(skip, count);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Customer[]> GetCustomersAsync(int skip, int count) {
            return base.Channel.GetCustomersAsync(skip, count);
        }
        
        public tp_api_demo.TPServiceReference.CustomerAddress[] GetCustomerAddresses(int id) {
            return base.Channel.GetCustomerAddresses(id);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.CustomerAddress[]> GetCustomerAddressesAsync(int id) {
            return base.Channel.GetCustomerAddressesAsync(id);
        }
        
        public tp_api_demo.TPServiceReference.Manufacturer[] GetManufacturers() {
            return base.Channel.GetManufacturers();
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Manufacturer[]> GetManufacturersAsync() {
            return base.Channel.GetManufacturersAsync();
        }
        
        public tp_api_demo.TPServiceReference.Order[] GetOrders(int skip, int count) {
            return base.Channel.GetOrders(skip, count);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Order[]> GetOrdersAsync(int skip, int count) {
            return base.Channel.GetOrdersAsync(skip, count);
        }
        
        public tp_api_demo.TPServiceReference.OrderProduct[] GetOrderProducts(int order) {
            return base.Channel.GetOrderProducts(order);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.OrderProduct[]> GetOrderProductsAsync(int order) {
            return base.Channel.GetOrderProductsAsync(order);
        }
        
        public tp_api_demo.TPServiceReference.Product[] GetProducts(int skip, int count) {
            return base.Channel.GetProducts(skip, count);
        }
        
        public System.Threading.Tasks.Task<tp_api_demo.TPServiceReference.Product[]> GetProductsAsync(int skip, int count) {
            return base.Channel.GetProductsAsync(skip, count);
        }
        
        public int AddCustomerAddress(tp_api_demo.TPServiceReference.CustomerAddress value) {
            return base.Channel.AddCustomerAddress(value);
        }
        
        public System.Threading.Tasks.Task<int> AddCustomerAddressAsync(tp_api_demo.TPServiceReference.CustomerAddress value) {
            return base.Channel.AddCustomerAddressAsync(value);
        }
        
        public int AddAttribute(tp_api_demo.TPServiceReference.Attribute value) {
            return base.Channel.AddAttribute(value);
        }
        
        public System.Threading.Tasks.Task<int> AddAttributeAsync(tp_api_demo.TPServiceReference.Attribute value) {
            return base.Channel.AddAttributeAsync(value);
        }
        
        public int AddCategory(tp_api_demo.TPServiceReference.Category value) {
            return base.Channel.AddCategory(value);
        }
        
        public System.Threading.Tasks.Task<int> AddCategoryAsync(tp_api_demo.TPServiceReference.Category value) {
            return base.Channel.AddCategoryAsync(value);
        }
        
        public int AddCustomer(tp_api_demo.TPServiceReference.Customer value) {
            return base.Channel.AddCustomer(value);
        }
        
        public System.Threading.Tasks.Task<int> AddCustomerAsync(tp_api_demo.TPServiceReference.Customer value) {
            return base.Channel.AddCustomerAsync(value);
        }
        
        public int AddManufacturer(tp_api_demo.TPServiceReference.Manufacturer value) {
            return base.Channel.AddManufacturer(value);
        }
        
        public System.Threading.Tasks.Task<int> AddManufacturerAsync(tp_api_demo.TPServiceReference.Manufacturer value) {
            return base.Channel.AddManufacturerAsync(value);
        }
        
        public int AddOrder(tp_api_demo.TPServiceReference.OrderRequest value) {
            return base.Channel.AddOrder(value);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(tp_api_demo.TPServiceReference.OrderRequest value) {
            return base.Channel.AddOrderAsync(value);
        }
        
        public int AddOrderStatus(tp_api_demo.TPServiceReference.OrderStatus value) {
            return base.Channel.AddOrderStatus(value);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderStatusAsync(tp_api_demo.TPServiceReference.OrderStatus value) {
            return base.Channel.AddOrderStatusAsync(value);
        }
        
        public int AddProduct(tp_api_demo.TPServiceReference.Product value) {
            return base.Channel.AddProduct(value);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAsync(tp_api_demo.TPServiceReference.Product value) {
            return base.Channel.AddProductAsync(value);
        }
        
        public int AddProductAttribute(tp_api_demo.TPServiceReference.ProductAttribute v) {
            return base.Channel.AddProductAttribute(v);
        }
        
        public System.Threading.Tasks.Task<int> AddProductAttributeAsync(tp_api_demo.TPServiceReference.ProductAttribute v) {
            return base.Channel.AddProductAttributeAsync(v);
        }
        
        public int AddProductStatus(tp_api_demo.TPServiceReference.ProductStatus value) {
            return base.Channel.AddProductStatus(value);
        }
        
        public System.Threading.Tasks.Task<int> AddProductStatusAsync(tp_api_demo.TPServiceReference.ProductStatus value) {
            return base.Channel.AddProductStatusAsync(value);
        }
        
        public bool SetAttribute(tp_api_demo.TPServiceReference.Attribute value) {
            return base.Channel.SetAttribute(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetAttributeAsync(tp_api_demo.TPServiceReference.Attribute value) {
            return base.Channel.SetAttributeAsync(value);
        }
        
        public bool SetCategory(tp_api_demo.TPServiceReference.Category value) {
            return base.Channel.SetCategory(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetCategoryAsync(tp_api_demo.TPServiceReference.Category value) {
            return base.Channel.SetCategoryAsync(value);
        }
        
        public bool SetCustomer(tp_api_demo.TPServiceReference.Customer value) {
            return base.Channel.SetCustomer(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetCustomerAsync(tp_api_demo.TPServiceReference.Customer value) {
            return base.Channel.SetCustomerAsync(value);
        }
        
        public bool SetCustomerAddress(tp_api_demo.TPServiceReference.CustomerAddress value) {
            return base.Channel.SetCustomerAddress(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetCustomerAddressAsync(tp_api_demo.TPServiceReference.CustomerAddress value) {
            return base.Channel.SetCustomerAddressAsync(value);
        }
        
        public bool SetManufacturer(tp_api_demo.TPServiceReference.Manufacturer value) {
            return base.Channel.SetManufacturer(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetManufacturerAsync(tp_api_demo.TPServiceReference.Manufacturer value) {
            return base.Channel.SetManufacturerAsync(value);
        }
        
        public bool SetOrderStatus(tp_api_demo.TPServiceReference.OrderStatus value) {
            return base.Channel.SetOrderStatus(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetOrderStatusAsync(tp_api_demo.TPServiceReference.OrderStatus value) {
            return base.Channel.SetOrderStatusAsync(value);
        }
        
        public bool SetProduct(tp_api_demo.TPServiceReference.Product value) {
            return base.Channel.SetProduct(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetProductAsync(tp_api_demo.TPServiceReference.Product value) {
            return base.Channel.SetProductAsync(value);
        }
        
        public bool SetProductAttribute(tp_api_demo.TPServiceReference.ProductAttribute value) {
            return base.Channel.SetProductAttribute(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetProductAttributeAsync(tp_api_demo.TPServiceReference.ProductAttribute value) {
            return base.Channel.SetProductAttributeAsync(value);
        }
        
        public bool SetProductStatus(tp_api_demo.TPServiceReference.ProductStatus value) {
            return base.Channel.SetProductStatus(value);
        }
        
        public System.Threading.Tasks.Task<bool> SetProductStatusAsync(tp_api_demo.TPServiceReference.ProductStatus value) {
            return base.Channel.SetProductStatusAsync(value);
        }
    }
}
