//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_lab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> address { get; set; }
        public virtual DbSet<Attribute> attribute { get; set; }
        public virtual DbSet<Category> category { get; set; }
        public virtual DbSet<Customer> customer { get; set; }
        public virtual DbSet<Manufacturer> manufacturer { get; set; }
        public virtual DbSet<Order> order { get; set; }
        public virtual DbSet<OrderStatus> order_status { get; set; }
        public virtual DbSet<Product> product { get; set; }
        public virtual DbSet<ProductAttribute> product_attribute { get; set; }
        public virtual DbSet<ProductStatus> product_status { get; set; }
        public virtual DbSet<OrderProduct> order_product { get; set; }
    }
}
