//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.attributes = new HashSet<ProductAttribute>();
            this.order_product = new HashSet<OrderProduct>();
        }
    
        public int id { get; set; }
        public Nullable<int> category_id { get; set; }
        public int manufacturer_id { get; set; }
        public int status_id { get; set; }
        public string name { get; set; }
        public string model { get; set; }
        public string description { get; set; }
        public decimal price { get; set; }
    
        public virtual Category category { get; set; }
        public virtual Manufacturer manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAttribute> attributes { get; set; }
        public virtual ProductStatus status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> order_product { get; set; }
    }
}
