//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAttribute
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int attribute_id { get; set; }
        public string value { get; set; }
    
        public virtual Attribute attribute { get; set; }
        public virtual Product product { get; set; }
    }
}
